apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: efrink29/manager:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB1_CONN
          valueFrom:
            secretKeyRef:
              name: db1-credentials
              key: connection-string
        - name: CRAWLER_1
          value: "crawler-1:8080"
        - name: CRAWLER_2
          value: "crawler-2:8080"
        - name: CRAWLER_3
          value: "crawler-3:8080"
        - name: MANAGER_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  selector:
    app: manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
